version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: karollaflores
      POSTGRES_PASSWORD: karollafloresdev
      POSTGRES_DB: karollaflores_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local